### ISSUE TITLE
Having trouble with Wikipedia notation

### ISSUE THREAD

**Issue by michaelsilver** [infolab-csail/WikipediaBase#23]
Some infobox attributes include strings wrapped in `!!!!!`, and seem to be caused by WikipediaBase having trouble with Wikipedia notation. For example: 
```
u'Highest\xa0elevation!!!!!elevation_max_footnotes!!!!!'
```
from `Template:Infobox settlement` seems to be having trouble with footnote notation. This happens in a lot of attributes when fetched with 
```
get_meta_infobox('<TEMPLATE_NAME>').rendered_keys()
```
Any ideas as to why this is happening?

Below is a list of tuples in the form `(attribute, [list of infoboxes])` for all fetchable attributes with such `!!!!!` strings -- hope this helps!
```
(u'!!!!!commander_title!!!!!', [u'Template:Infobox national military'])
(u'!!!!!officetype!!!!!!!!!!office_type!!!!!s', [u'Template:Infobox law enforcement agency'])
(u'!!!!!tv!!!!!', [u'Template:Infobox pulps character'])
(u'!!!!!reign-type!!!!!', [u'Template:Infobox noble', u'Template:Infobox nobility'])
(u'!!!!!established_title!!!!!', [u'Template:Infobox settlement'])
(u'!!!!!yearDstart!!!!!\u2013!!!!!yearDend!!!!!', [u'Template:Infobox rugby league biography'])
(u'!!!!!district_label!!!!!', [u'Template:Infobox constituency'])
(u'Coat of arms of\xa0!!!!!name!!!!!Coat of arms', [u'Template:Infobox settlement'])
(u'!!!!!ru_sevensnationalyears!!!!!', [u'Template:Infobox rugby biography'])
(u'!!!!!ru_provinceyears!!!!!', [u'Template:Infobox rugby biography'])
(u'!!!!!manageyears!!!!!', [u'Template:Infobox cyclist'])
(u'!!!!!colors_label!!!!!', [u'Template:Infobox military unit'])
(u'!!!!!smartcardname!!!!!</th>', [u'Template:Infobox station'])
(u'!!!!!com-years!!!!!', [u'Template:Infobox heritage railway'])
(u'Commercial and public consumption(% of total,\xa0!!!!!commercialpublicyear!!!!!)', [u'Template:Infobox electricity sector'])
(u'!!!!!radio!!!!!', [u'Template:Infobox pulps character'])
(u'!!!!!league!!!!! team', [u'Template:Infobox lacrosse player'])
(u'!!!!!ownership-registration-sections!!!!!', [u'Template:Infobox state gun laws'])
(u'!!!!!coach_years!!!!!', [u'Template:Infobox college coach'])
(u'Industrial consumption(% of total,\xa0!!!!!industrialyear!!!!!)', [u'Template:Infobox electricity sector'])
(u'\u2022\xa0Metro!!!!!area_metro_footnotes!!!!!', [u'Template:Infobox settlement'])
(u'!!!!!Series!!!!! championships', [u'Template:Infobox independent baseball team', u'Template:Infobox baseball team'])
(u'!!!!!rl_clubyears!!!!!', [u'Template:Infobox rugby biography'])
(u'!!!!!league_link!!!!!', [u'Template:Infobox rugby league team season'])
(u'!!!!!player_years!!!!!', [u'Template:Infobox college coach'])
(u'!!!!!countrytag!!!!!', [u'Template:Infobox rugby league football competition'])
(u'!!!!!altL!!!!!', [u'Template:Infobox drug'])
(u'!!!!!ru_coachyearBstart!!!!!\u2013!!!!!ru_coachyearBend!!!!!', [u'Template:Infobox rugby league biography'])
(u'!!!!!administrating_years!!!!!', [u'Template:Infobox gridiron football person'])
(u'!!!!!blank_name!!!!!', [u'Template:Infobox settlement', u'Template:Infobox river'])
(u'!!!!!dissolved_state!!!!!', [u'Template:Infobox union'])
(u'!!!!!bishop_title!!!!!', [u'Template:Infobox diocese'])
(u'!!!!!stationtype!!!!!!!!!!station_type!!!!!s', [u'Template:Infobox law enforcement agency'])
(u'!!!!!season!!!!! placing', [u'Template:Infobox netball team'])
(u'!!!!!nationalyears!!!!!', [u'Template:Infobox handball biography', u'Template:Infobox volleyball biography'])
(u'!!!!!office_label!!!!!', [u'Template:Infobox cabinet'])
(u'!!!!!manufacturing-sections!!!!!', [u'Template:Infobox state gun laws'])
(u'!!!!!lockuptype!!!!!!!!!!lockup_type!!!!!s', [u'Template:Infobox law enforcement agency'])
(u'Least\xa0populous\xa0!!!!!region_type!!!!!', [u'Template:Infobox census'])
(u'!!!!!MoM_title!!!!!', [u'Template:Infobox rugby league football match'])
(u'!!!!!map_cue!!!!!!!!!!map_text!!!!!', [u'Template:Infobox aqueduct', u'Template:Infobox pier', u'Template:Infobox bridge'])
(u'!!!!!ru_yearCstart!!!!!\u2013!!!!!ru_yearCend!!!!!', [u'Template:Infobox rugby league biography'])
(u'!!!!!direction_b!!!!!\xa0end', [u'Template:Infobox street'])
(u'!!!!!restricted-persons-sections!!!!!', [u'Template:Infobox state gun laws'])
(u'!!!!!prev!!!!!\xa0\u2190', [u'Template:Infobox league season'])
(u'Distance to !!!!!endb!!!!!', [u'Template:Infobox waterlock'])
(u'!!!!!blank_label!!!!!', [u'Template:Infobox event', u'Template:Infobox game', u'Template:Infobox sports team', u'Template:Infobox sport club'])
(u'!!!!!oversight_label!!!!!', [u'Template:Infobox secondary school'])
(u'!!!!!currentyears!!!!!', [u'Template:Infobox volleyball biography'])
(u'Installed capacity\xa0(!!!!!capacityyear!!!!!)', [u'Template:Infobox electricity sector'])
(u'!!!!!local_council_label!!!!!', [u'Template:Infobox constituency'])
(u'!!!!!coordinate_title!!!!!', [u'Template:Infobox hotspot custom'])
(u'!!!!!direction_a!!!!!\xa0end', [u'Template:Infobox street'])
(u'!!!!!comic!!!!!', [u'Template:Infobox pulps character'])
(u'!!!!!script_name!!!!!', [u'Template:Infobox deity'])
(u'!!!!!members_label!!!!!', [u'Template:Infobox constituency'])
(u'GHG emissions from electricity generation\xa0(!!!!!greenhouseyear!!!!!)', [u'Template:Infobox electricity sector'])
(u'< \xa0!!!!!last!!!!!', [u'Template:Infobox rugby league football match'])
(u'-\xa0!!!!!PopulationSecondYear!!!!!', [u'Template:Infobox historic subdivision'])
(u'Argument of peri!!!!!apsis!!!!!', [u'Template:Infobox spaceflight'])
(u'!!!!!games!!!!! appearances', [u'Template:Infobox country at games'])
(u'!!!!!beginning_label!!!!!', [u'Template:Infobox historic site'])
(u'!!!!!postal_code_type!!!!!', [u'Template:Infobox settlement'])
(u'Total circulation(!!!!!circulation_year!!!!!)', [u'Template:Infobox magazine'])
(u'!!!!!chrtitle!!!!!', [u'Template:Infobox football club', u'Template:Infobox football club season'])
(u'!!!!!lost-stolen-registration-sections!!!!!', [u'Template:Infobox state gun laws'])
(u'!!!!!head_label!!!!!', [u'Template:Infobox institute', u'Template:Infobox academic division', u'Template:Infobox university', u'Template:Infobox secondary school', u'Template:Infobox laboratory', u'Template:Infobox college'])
(u'!!!!!concealed-carry-sections!!!!!', [u'Template:Infobox state gun laws'])
(u'\u2190 Previous season!!!!!prevseason!!!!!', [u'Template:Infobox football club season2'])
(u'!!!!!Races!!!!!', [u'Template:Infobox racing car'])
(u'!!!!!area_code_type!!!!!', [u'Template:Infobox settlement'])
(u'!!!!!years!!!!!', [u'Template:Infobox pro football player', u'Template:Infobox handball biography', u'Template:Infobox heritage railway', u'Template:Infobox volleyball biography'])
(u'Only ODI (cap\xa0!!!!!odicap!!!!!)', [u'Template:Infobox cricketer', u'Template:Infobox cricketer biography'])
(u'!!!!!mainaffiliation!!!!! affiliation', [u'Template:Infobox rugby league'])
(u'!!!!!free_label!!!!!', [u'Template:Infobox university', u'Template:Infobox school district', u'Template:Infobox examination', u'Template:Infobox laboratory', u'Template:Infobox students union', u'Template:Infobox college'])
(u'!!!!!yearAstart!!!!!\u2013!!!!!yearAend!!!!!', [u'Template:Infobox rugby league biography'])
(u'Share of private financing\xa0(!!!!!privatefinanceyear!!!!!)', [u'Template:Infobox electricity sector'])
(u'!!!!!rl_coachyears!!!!!', [u'Template:Infobox rugby biography'])
(u'Most\xa0populous\xa0!!!!!region_type!!!!!', [u'Template:Infobox census'])
(u'!!!!!coachyearBstart!!!!!\u2013!!!!!coachyearBend!!!!!', [u'Template:Infobox rugby league biography'])
(u'!!!!!stock_exchange!!!!!', [u'Template:Infobox mine', u'Template:Infobox gold mine'])
(u'!!!!!other_years!!!!!', [u'Template:Infobox gridiron football person'])
(u'!!!!!leader_title!!!!!', [u'Template:Infobox sporting event organization', u'Template:Infobox religion', u'Template:Infobox organization', u'Template:Infobox hockey league'])
(u'!!!!!Last!!!!!', [u'Template:Infobox halftime show'])
(u'Impact factor(!!!!!impact-year!!!!!)', [u'Template:Infobox journal'])
(u'!!!!!mgrtitle!!!!!', [u'Template:Infobox football club', u'Template:Infobox football club season'])
(u'<\xa0!!!!!last!!!!!', [u'Template:Infobox film awards'])
(u'-\xa0!!!!!AreaSecondYear!!!!!', [u'Template:Infobox historic subdivision'])
(u'!!!!!alien-persons-sections!!!!!', [u'Template:Infobox state gun laws'])
(u'!!!!!map_cue!!!!!', [u'Template:Infobox waterlock'])
(u'-\xa0!!!!!DensityFirstYear!!!!!', [u'Template:Infobox historic subdivision'])
(u'!!!!!equipment_label!!!!!', [u'Template:Infobox military unit'])
(u'!!!!!currentposition!!!!!', [u'Template:Infobox college football player'])
(u'!!!!!ru_nationalyears!!!!!', [u'Template:Infobox rugby biography'])
(u'!!!!!film!!!!!', [u'Template:Infobox pulps character'])
(u'!!!!!dealer-sections!!!!!', [u'Template:Infobox state gun laws'])
(u'Most\xa0!!!!!type!!!!! wins', [u'Template:Infobox bowl series'])
(u'!!!!!cup!!!!!', [u'Template:Infobox rugby league team season'])
(u'!!!!!underage-persons-sections!!!!!', [u'Template:Infobox state gun laws'])
(u'!!!!!country_type!!!!!', [u'Template:Infobox mountain range'])
(u'!!!!!unsworntype!!!!!!!!!!unsworn_type!!!!!s', [u'Template:Infobox law enforcement agency'])
(u'!!!!!flag_type!!!!!', [u'Template:Infobox former subdivision', u'Template:Infobox former country'])
(u'!!!!!transportation-sections!!!!!', [u'Template:Infobox state gun laws'])
(u'\u2190\xa0!!!!!previous!!!!! (previous)', [u'Template:Infobox badminton event', u'Template:Infobox cricket series'])
(u'!!!!!youthyears!!!!!', [u'Template:Infobox handball biography'])
(u'!!!!!championtag!!!!!', [u'Template:Infobox rugby league football competition'])
(u'-\xa0!!!!!AreaFirstYear!!!!!', [u'Template:Infobox historic subdivision'])
(u'!!!!!sworntype!!!!!!!!!!sworn_type!!!!!s', [u'Template:Infobox law enforcement agency'])
(u'!!!!!coachyearAstart!!!!!\u2013!!!!!coachyearAend!!!!!', [u'Template:Infobox rugby league biography'])
(u'Residential consumption(% of total,\xa0!!!!!residentialyear!!!!!)', [u'Template:Infobox electricity sector'])
(u'\u2022\xa0Rural!!!!!area_rural_footnotes!!!!!', [u'Template:Infobox settlement'])
(u'!!!!!rl_amateuryears!!!!!', [u'Template:Infobox rugby biography'])
(u'-\xa0!!!!!AreaThirdYear!!!!!', [u'Template:Infobox historic subdivision'])
(u'!!!!!finals!!!!! champions', [u'Template:Infobox sports season'])
(u'!!!!!coaching_years!!!!!', [u'Template:Infobox gridiron football person'])
(u'Batted:\xa0!!!!!bats!!!!!', [u'Template:Infobox baseball biography'])
(u'!!!!!restricted-firearms-sections!!!!!', [u'Template:Infobox state gun laws'])
(u'!!!!!category_label!!!!!', [u'Template:Infobox secondary school'])
(u'!!!!!league!!!!! team\xa0(P)Cur. teamFormer teams', [u'Template:Infobox ice hockey player'])
(u'!!!!!spouse-type!!!!!', [u'Template:Infobox noble', u'Template:Infobox nobility'])
(u'<\xa0\xa0!!!!!Wprevious!!!!!', [u'Template:Infobox games'])
(u'!!!!!series!!!!! ranking', [u'Template:Infobox cycling team season'])
(u'Maximum pressure (!!!!!pressure_method!!!!!)', [u'Template:Infobox firearm cartridge'])
(u'!!!!!leadershiptitle!!!!!', [u'Template:Infobox port'])
(u'!!!!!artistic_staff_type!!!!!', [u'Template:Infobox ballet company'])
(u'!!!!!gun-show-sections!!!!!', [u'Template:Infobox state gun laws'])
(u'Semi-major axis of outer\xa0planet (!!!!!outerplanetname!!!!!)', [u'Template:Infobox planetary system'])
(u'Lowest\xa0elevation!!!!!elevation_min_footnotes!!!!!', [u'Template:Infobox settlement'])
(u'\u2022\xa0Rural!!!!!population_rural_footnotes!!!!!', [u'Template:Infobox settlement'])
(u'!!!!!ru_yearEstart!!!!!\u2013!!!!!ru_yearEend!!!!!', [u'Template:Infobox rugby league biography'])
(u'Share of self-financing by utilities\xa0(!!!!!selffinanceyear!!!!!)', [u'Template:Infobox electricity sector'])
(u'Parent\xa0!!!!!type!!!!!', [u'Template:Infobox government agency'])
(u'\u2190 !!!!!previous_year!!!!! (previous)', [u'Template:Infobox hockey'])
(u'All-time series \xa0(!!!!!league!!!!! only)', [u'Template:Infobox sports rivalry'])
(u'!!!!!CodeName!!!!!', [u'Template:Infobox historic subdivision'])
(u'!!!!!open-carry-sections!!!!!', [u'Template:Infobox state gun laws'])
(u'!!!!!ru_yearBstart!!!!!\u2013!!!!!ru_yearBend!!!!!', [u'Template:Infobox rugby league biography'])
(u'!!!!!parts_type!!!!!', [u'Template:Infobox settlement'])
(u'!!!!!region!!!!! affiliation', [u'Template:Infobox rugby league'])
(u'!!!!!chairman_label!!!!!', [u'Template:Infobox secondary school'])
(u'!!!!!Extra_Title!!!!!', [u'Template:Infobox paranormal term'])
(u'!!!!!classification_label!!!!!', [u'Template:Infobox animal breed'])
(u'!!!!!TPB!!!!!', [u'Template:Infobox comics character and title', u'Template:Infobox comics team and title', u'Template:Infobox comic book title', u'Template:Infobox comics meta series', u'Template:Infobox comics species and title', u'Template:Infobox comics set and title', u'Template:Infobox comics object and title'])
(u'(!!!!!home_league!!!!!)', [u'Template:Infobox rugby league football match'])
(u'Ap!!!!!apsis!!!!!', [u'Template:Infobox planet'])
(u'!!!!!fourth_officer_title!!!!!', [u'Template:Infobox accounting body'])
(u'!!!!!tournament!!!!!', [u'Template:Infobox darts player'])
(u'\u2022\xa0!!!!!leader_title!!!!!', [u'Template:Infobox settlement'])
(u'!!!!!minister_title!!!!!', [u'Template:Infobox national military'])
(u'Population\xa0(!!!!!population_year!!!!!)\xa0\u2022\xa0Voting age\xa0\u2022\xa0Citizen voting age', [u'Template:Infobox legislative district'])
(u'!!!!!firstlabel!!!!!', [u'Template:Infobox sport'])
(u'!!!!!second_officer_title!!!!!', [u'Template:Infobox accounting body'])
(u'!!!!!convicted-persons-sections!!!!!', [u'Template:Infobox state gun laws'])
(u'!!!!!party_label!!!!!', [u'Template:Infobox constituency'])
(u'Rural consumption(% of total,\xa0!!!!!ruralyear!!!!!)', [u'Template:Infobox electricity sector'])
(u'!!!!!proyears!!!!!', [u'Template:Infobox cyclist'])
(u'!!!!!captaintitle!!!!!', [u'Template:Infobox cricket club season'])
(u'!!!!!ru_coachyearCstart!!!!!\u2013!!!!!ru_coachyearCend!!!!!', [u'Template:Infobox rugby league biography'])
(u'Ethnic\xa0groups (!!!!!ethnic_groups_year!!!!!)', [u'Template:Infobox country'])
(u'!!!!!IF_abbr!!!!! members page', [u'Template:Infobox national sports federations'])
(u'!!!!!ru_amateuryears!!!!!', [u'Template:Infobox rugby biography'])
(u'!!!!!ru_yearAstart!!!!!\u2013!!!!!ru_yearAend!!!!!', [u'Template:Infobox rugby league biography'])
(u'Membership \xa0(!!!!!membership_year!!!!!)', [u'Template:Infobox political party'])
(u'Highest\xa0elevation!!!!!elevation_max_footnotes!!!!!', [u'Template:Infobox settlement'])
(u'Distance to !!!!!enda!!!!!', [u'Template:Infobox waterlock'])
(u'!!!!!CEO_title!!!!!', [u'Template:Infobox rugby league team season'])
(u'!!!!!coachtitle!!!!!', [u'Template:Infobox cricket club season'])
(u'Share of government financing\xa0(!!!!!governmentfinanceyear!!!!!)', [u'Template:Infobox electricity sector'])
(u'Commercial consumption(% of total,\xa0!!!!!commercialyear!!!!!)', [u'Template:Infobox electricity sector'])
(u'!!!!!playing_years!!!!!', [u'Template:Infobox gridiron football person'])
(u'!!!!!editor_title!!!!!', [u'Template:Infobox magazine'])
(u'!!!!!state_type!!!!!', [u'Template:Infobox mountain range'])
(u'Other\xa0!!!!!nameforarea!!!!!(s):', [u'Template:Infobox rail company'])
(u'!!!!!placeofburial_label!!!!!', [u'Template:Infobox military person'])
(u'\u2022\xa0!!!!!total_type!!!!!', [u'Template:Infobox settlement'])
(u'!!!!!suc-type!!!!!', [u'Template:Infobox monarch', u'Template:Infobox nobility', u'Template:Infobox noble'])
(u'!!!!!Season!!!!!', [u'Template:Infobox independent baseball team', u'Template:Infobox baseball team'])
(u'!!!!!poolnames!!!!!', [u'Template:Infobox swimming venue'])
(u'!!!!!unittype!!!!!!!!!!unit_type!!!!!s', [u'Template:Infobox law enforcement agency'])
(u'!!!!!home_total!!!!!', [u'Template:Infobox rugby league football match'])
(u'-\xa0!!!!!DensitySecondYear!!!!!', [u'Template:Infobox historic subdivision'])
(u'Elevation!!!!!elevation_footnotes!!!!!', [u'Template:Infobox frazione', u'Template:Infobox settlement'])
(u'!!!!!testname!!!!! Average', [u'Template:Infobox secondary school'])
(u'\u2022\xa0Urban!!!!!population_urban_footnotes!!!!!', [u'Template:Infobox settlement'])
(u'Peri!!!!!apsis!!!!!', [u'Template:Infobox planet', u'Template:Infobox spaceflight'])
(u'!!!!!direction_a!!!!!\xa0end:', [u'Template:Infobox road'])
(u'Argument\xa0of peri!!!!!apsis!!!!!', [u'Template:Infobox planet'])
(u'<\xa0\xa0!!!!!WpreviousS!!!!!', [u'Template:Infobox games'])
(u'\xab!!!!!prev!!!!!', [u'Template:Infobox individual darts tournament'])
(u'!!!!!admin_years!!!!!', [u'Template:Infobox college coach'])
(u'!!!!!city_type!!!!!', [u'Template:Infobox mountain range'])
(u'Number of\xa0!!!!!type!!!!!s', [u'Template:Infobox bowl series'])
(u'!!!!!founding_person_type!!!!!', [u'Template:Infobox ballet company'])
(u'!!!!!district_type!!!!!', [u'Template:Infobox mountain range'])
(u'<\xa0!!!!!before!!!!!', [u'Template:Infobox legislative session'])
(u'!!!!!IF_abbr!!!!! member since', [u'Template:Infobox national sports federations'])
(u'Only Test (cap\xa0!!!!!testcap!!!!!)', [u'Template:Infobox cricketer', u'Template:Infobox cricketer biography'])
(u'!!!!!direction_b!!!!!\xa0end:', [u'Template:Infobox road'])
(u'\u2190\xa0!!!!!previous!!!!!', [u'Template:Infobox ice hockey game', u'Template:Infobox sport tournament'])
(u'Average electricity use\xa0(!!!!!useyear!!!!!)', [u'Template:Infobox electricity sector'])
(u'!!!!!battle_honours_label!!!!!', [u'Template:Infobox military unit'])
(u'!!!!!owntitle!!!!!', [u'Template:Infobox football club'])
(u'!!!!!yearBstart!!!!!\u2013!!!!!yearBend!!!!!', [u'Template:Infobox rugby league biography'])
(u'HDI (!!!!!HDI_year!!!!!)', [u'Template:Infobox country'])
(u'!!!!!third_officer_title!!!!!', [u'Template:Infobox accounting body'])
(u'!!!!!highest_officer_title!!!!!', [u'Template:Infobox accounting body'])
(u'!!!!!finals!!!!! MVP', [u'Template:Infobox sports season'])
(u'Largest\xa0!!!!!largest_settlement_type!!!!!', [u'Template:Infobox country'])
(u'!!!!!previous_mission!!!!!', [u'Template:Infobox space mission'])
(u'File:Kit baseball cap!!!!!h pattern cap!!!!!.png\nFile:Kit left arm!!!!!h pattern la!!!!!.png\nFile:Kit left arm.svg\nFile:Kit body!!!!!h pattern b!!!!!.png\nFile:Kit right arm!!!!!h pattern ra!!!!!.png\nFile:Kit right arm.svg\nFile:Kit trousers!!!!!h pattern pants!!!!!.png\nFile:Kit baseball socks.svg\n\n!!!!!h_title!!!!!', [u'Template:Infobox independent baseball team', u'Template:Infobox baseball team'])
(u'!!!!!gender_label!!!!!', [u'Template:Infobox secondary school'])
(u'Designated\xa0!!!!!NRHP_TYPE!!!!!', [u'Template:Infobox nrhp'])
(u'Apo!!!!!apsis!!!!!', [u'Template:Infobox planet', u'Template:Infobox spaceflight'])
(u'Relegated to\xa0!!!!!relegate_to!!!!!', [u'Template:Infobox sports season'])
(u'!!!!!ru_coachyearAstart!!!!!\u2013!!!!!ru_coachyearAend!!!!!', [u'Template:Infobox rugby league biography'])
(u'!!!!!season_champ_name!!!!!', [u'Template:Infobox sports season'])
(u'<\xa0\xa0!!!!!previous!!!!!', [u'Template:Infobox games'])
(u'!!!!!region_type!!!!!', [u'Template:Infobox mountain range'])
(u'!!!!!ceotag!!!!!', [u'Template:Infobox rugby league football competition'])
(u'!!!!!patron_title!!!!!', [u'Template:Infobox diocese'])
(u'!!!!!coachyearCstart!!!!!\u2013!!!!!coachyearCend!!!!!', [u'Template:Infobox rugby league biography'])
(u'!!!!!previous_year!!!!!\xa0\u2190', [u'Template:Infobox election'])
(u'!!!!!amateur_title!!!!!:', [u'Template:Infobox gridiron football person'])
(u'!!!!!ru_clubyears!!!!!', [u'Template:Infobox rugby biography'])
(u'Average residential tariff(US$/kW\xb7h,\xa0!!!!!rtariffyear!!!!!)', [u'Template:Infobox electricity sector'])
(u'!!!!!purchase-registration-sections!!!!!', [u'Template:Infobox state gun laws'])
(u'!!!!!subdivision_type!!!!!', [u'Template:Infobox settlement'])
(u'!!!!!constitution-sections!!!!!', [u'Template:Infobox state gun laws'])
(u'!!!!!restricted-ammunition-sections!!!!!', [u'Template:Infobox state gun laws'])
(u'!!!!!leader_type!!!!!', [u'Template:Infobox bus transit', u'Template:Infobox bus company'])
(u'!!!!!ballet_staff_type!!!!!', [u'Template:Infobox ballet company'])
(u'!!!!!league_champ_name!!!!!', [u'Template:Infobox sports season'])
(u'Transmission losses\xa0(!!!!!translossesyear!!!!!)', [u'Template:Infobox electricity sector'])
(u'!!!!!association!!!!!', [u'Template:Infobox school athletics'])
(u'!!!!!playoffs!!!!! MVP', [u'Template:Infobox sports season'])
(u'Average commercial tariff(US$/kW\xb7h,\xa0!!!!!ctariffyear!!!!!)', [u'Template:Infobox electricity sector'])
(u'Flag of\xa0!!!!!common_name!!!!!', [u'Template:Infobox country'])
(u'-\xa0!!!!!PopulationLastYear!!!!!', [u'Template:Infobox historic subdivision'])
(u'!!!!!ru_yearDstart!!!!!\u2013!!!!!ru_yearDend!!!!!', [u'Template:Infobox rugby league biography'])
(u'!!!!!yearEstart!!!!!\u2013!!!!!yearEend!!!!!', [u'Template:Infobox rugby league biography'])
(u'!!!!!home!!!!!', [u'Template:Infobox rugby league football match'])
(u'!!!!!admin_center_type!!!!!', [u'Template:Infobox country'])
(u'!!!!!issuing_authority_title!!!!!', [u'Template:Infobox currency'])
(u'!!!!!coach_title!!!!!', [u'Template:Infobox rugby league team season'])
(u'\u2022\xa0Mayor (!!!!!mayor_as_of!!!!!)', [u'Template:Infobox kommune'])
(u'\u2190\xa0Previous"!!!!!Prev!!!!!"', [u'Template:Infobox television episode'])
(u'!!!!!restricted-accessories-sections!!!!!', [u'Template:Infobox state gun laws'])
(u'!!!!!titleyears!!!!!', [u'Template:Infobox handball biography'])
(u'!!!!!extinct_title!!!!!', [u'Template:Infobox settlement'])
(u'< !!!!!before_year!!!!!', [u'Template:Infobox tennis event'])
(u'!!!!!ru_coachyears!!!!!', [u'Template:Infobox rugby biography'])
(u'!!!!!languages_type!!!!!', [u'Template:Infobox country'])
(u'Distribution losses\xa0(!!!!!distlossesyear!!!!!)', [u'Template:Infobox electricity sector'])
(u'!!!!!last_tour!!!!!', [u'Template:Infobox concert tour'])
(u'Delisted\xa0!!!!!NRHP_TYPE!!!!!', [u'Template:Infobox nrhp'])
(u'-\xa0!!!!!DensityLastYear!!!!!', [u'Template:Infobox historic subdivision'])
(u'!!!!!battles_label!!!!!', [u'Template:Infobox military person'])
(u'Number of affiliated\xa0!!!!!sport!!!!! clubs', [u'Template:Infobox national sports federations'])
(u'<\xa0!!!!!previous!!!!!', [u'Template:Infobox award'])
(u'!!!!!resultyears!!!!!', [u'Template:Infobox volleyball biography'])
(u'!!!!!preemption-sections!!!!!', [u'Template:Infobox state gun laws'])
(u'!!!!!id_type!!!!!', [u'Template:Infobox bridge'])
(u'!!!!!overseastitle!!!!!', [u'Template:Infobox cricket club season'])
(u'<\xa0\xa0!!!!!Sprevious!!!!!', [u'Template:Infobox games'])
(u'!!!!!league_type!!!!!', [u'Template:Infobox sportsperson'])
(u'!!!!!extralabel!!!!!', [u'Template:Infobox unit', u'Template:Infobox country languages'])
(u'-\xa0!!!!!DensityThirdYear!!!!!', [u'Template:Infobox historic subdivision'])
(u'\u2022\xa0Urban!!!!!area_urban_footnotes!!!!!', [u'Template:Infobox settlement'])
(u'!!!!!region_label!!!!!', [u'Template:Infobox constituency'])
(u'<\xa0\xa0!!!!!SpreviousS!!!!!', [u'Template:Infobox games'])
(u'-\xa0!!!!!PopulationFirstYear!!!!!', [u'Template:Infobox historic subdivision'])
(u'Gini\xa0(!!!!!Gini_year!!!!!)', [u'Template:Infobox country'])
(u'Public sector consumption(% of total,\xa0!!!!!publicyear!!!!!)', [u'Template:Infobox electricity sector'])
(u'!!!!!seat_type!!!!!', [u'Template:Infobox settlement'])
(u'!!!!!yearCstart!!!!!\u2013!!!!!yearCend!!!!!', [u'Template:Infobox rugby league biography'])
(u'!!!!!rl_nationalyears!!!!!', [u'Template:Infobox rugby biography'])
(u'\u2022\xa0Metro!!!!!population_metro_footnotes!!!!!', [u'Template:Infobox settlement'])
(u'-\xa0!!!!!PopulationThirdYear!!!!!', [u'Template:Infobox historic subdivision'])
(u'!!!!!anthem_title!!!!!', [u'Template:Infobox rugby league football match'])
(u'Food energy(per\xa0!!!!!serving_size!!!!! serving)', [u'Template:Infobox prepared food'])
(u'!!!!!abolished_label!!!!!', [u'Template:Infobox constituency'])
(u'!!!!!trait_label!!!!!', [u'Template:Infobox animal breed'])
(u'!!!!!amateuryears!!!!!', [u'Template:Infobox cyclist'])
(u'Promoted from\xa0!!!!!promote_from!!!!!', [u'Template:Infobox sports season'])
(u'!!!!!prev!!!!!(!!!!!prev_no!!!!!)', [u'Template:Infobox song'])
(u'!!!!!season!!!!!', [u'Template:Infobox football club', u'Template:Infobox rugby league club', u'Template:Infobox rugby team', u'Template:Infobox cycling team', u'Template:Infobox floorball club', u'Template:Infobox volleyball club'])
(u'\u2190\xa0!!!!!prevseason!!!!!', [u'Template:Infobox football tournament season', u'Template:Infobox rugby team', u'Template:Infobox football club season', u'Template:Infobox squash tournament', u'Template:Infobox cricket club season'])
(u'Most\xa0!!!!!type!!!!! appearances', [u'Template:Infobox bowl series'])
(u'Most\xa0!!!!!type!!!!! championships', [u'Template:Infobox bowl series'])
(u'Average industrial tariff(US$/kW\xb7h,\xa0!!!!!itariffyear!!!!!)', [u'Template:Infobox electricity sector'])
(u'!!!!!last_concert!!!!!', [u'Template:Infobox concert'])
(u'!!!!!preceded_by!!!!!', [u'Template:Infobox film festival'])
(u'Overviewed by\xa0!!!!!overviewtype!!!!!!!!!!overview_type!!!!!', [u'Template:Infobox law enforcement agency'])
(u'!!!!!coachyears!!!!!', [u'Template:Infobox volleyball biography'])
(u'!!!!!commander-in-chief_title!!!!!', [u'Template:Infobox national military'])
(u'!!!!!membership_type!!!!!', [u'Template:Infobox country'])
(u'Number of\xa0!!!!!sport!!!!! clubs', [u'Template:Infobox national sports federations'])
(u'!!!!!canonized_label!!!!!', [u'Template:Infobox martyrs'])
(u'Passengers (!!!!!pass_year!!!!!)</th>', [u'Template:Infobox station'])
(u'\u2190 [[File:Template:Infobox road/shield/!!!!!COUNTRY!!!!!|x20px|link=|alt=]] [[Template:Infobox road/link/!!!!!COUNTRY!!!!!|]]', [u'Template:Infobox road'])
(u'!!!!!private-sections!!!!!', [u'Template:Infobox state gun laws'])
(u'!!!!!local-regulation-sections!!!!!', [u'Template:Infobox state gun laws'])
(u'!!!!!stageyears!!!!!', [u'Template:Infobox heritage railway'])
(u'!!!!!grades_label!!!!!', [u'Template:Infobox secondary school'])
(u'!!!!!garrison_label!!!!!', [u'Template:Infobox military unit'])
(u'Annual investment in electricity\xa0(!!!!!investmentyear!!!!!)', [u'Template:Infobox electricity sector'])
(u'File:Kit body unknown.png\n!!!!!h_title!!!!! jersey\nTeam colours\nTeam colours\n\n!!!!!h_title!!!!!', [u'Template:Infobox national wheelchair rugby team', u'Template:Infobox national basketball team'])
(u'Main\xa0!!!!!nameforarea!!!!!(s):', [u'Template:Infobox rail company'])
(u'-\xa0!!!!!AreaLastYear!!!!!', [u'Template:Infobox historic subdivision'])
(u'!!!!!restricted-places-sections!!!!!', [u'Template:Infobox state gun laws'])
(u'\u2022\xa0Estimate\xa0(!!!!!pop_est_as_of!!!!!)!!!!!pop_est_footnotes!!!!!', [u'Template:Infobox settlement'])
(u'!!!!!identification_symbol_label!!!!!', [u'Template:Infobox military unit'])
(u'\u2190\xa0!!!!!previous_mission!!!!!', [u'Template:Infobox spaceflight'])
(u'!!!!!city_vs_country_years!!!!!', [u'Template:Infobox rugby biography'])
(u'!!!!!sooyears!!!!!', [u'Template:Infobox rugby biography'])
(u'\u2190\xa0!!!!!prev!!!!!', [u'Template:Infobox squash championship'])
```

**Comment by fakedrake** [comment]
`MetaInfobox` is mostly for internal use. Wikipediabase wraps the infobox attribute name in '!!!!!' and sets it as the attribute value. Then it renders it and looks for !!!!!attribute_name!!!!! to see which *rendered* attributes are affected by each unrendered ones. So the behavior you are seeing is the intended.

Hope I addressed the issue.

**Comment by michaelsilver** [comment]
Thank you for your response. I use `MetaInfobox` to extract all unrendered ==> rendered attribute mappings because your WikiBase does a really great job at it! I'm wondering whether I am missing information when I get '!!!!!' wrapped attributes. Should I just delete those mappings? Or, can I replace them with useful info? 

Could we set up a Skype call to talk about '!!!!!' because I still don't quite understand what they signify and when/why they occur -- perhaps that would be faster than to continue messaging about it.

**Comment by fakedrake** [comment]
Just to mention it here as well for completeness: the rendered attribute names that contain `!!!!` depend on other attributes. Eg if an infobox has unrendered attributes `unrendered_foo` and `unrendered_bar` and wikipediabase claims that

`unrendered_bar -> Rendered Bar` and `unrendered_foo` -> `Foo !!!!unrendered_bar!!!!` it means that this infobox:

    unrendered_foo = "Foo value"
    unrendered_bar = "Bar value"

Will become something like:

    | Attribute        | Value     |
    |------------------+-----------|
    | Foo Bar value | Foo value |
    | Rendered bar     | Bar value |

Which means that the rendered attribute name of `unrendered_foo` depends on the value of bar. Thus it can't be generically induced for all infoboxes of the said type apriori and should probably be ignored. 

The task of this is to make a special case for this in `MetaInfobox`to not return these.

**Comment by alvaromorales** [comment]
Duplicate of #90
