### ISSUE TITLE
First-sentence date parsing should prefer precision to recall

### ISSUE THREAD

**Issue by sfelshin** [infolab-csail/WikipediaBase#94]
Currently Beethoven appears to have been born in the year 17:

    (get "wikibase-person" "Ludwig van Beethoven" (:CODE "BIRTH-DATE"))
    ((:yyyymmdd 00170000))

The first sentence for our dear friend is:

> Ludwig van Beethoven (Listeni/ˈlʊdvɪɡ væn ˈbeɪˌtoʊvən/; German: [ˈluːtvɪç fan ˈbeːtˌhoˑfn̩] ( listen); baptised 17 December 1770[1] – 26 March 1827)

Admittedly that's hard to parse, but if it's too hard, then `wikibase-person` should give up and return the date in `:html` format rather than `:yyyymmdd`, or it should give up entirely and throw some sort of error.  It should not claim that Beethoven could have had Christ for a baby sitter.

**Comment by sfelshin** [comment]
Another example of bad date parsing:

    (get "wikibase-person" "Wolfgang Amadeus Mozart" (:code "BIRTH-DATE"))
    ((:yyyymmdd 00010000))

In this case the first sentence is

> Wolfgang Amadeus Mozart (German: [ˈvɔlfɡaŋ amaˈdeːʊs ˈmoːtsaʁt], English see fn.;[1] 27 January 1756 – 5 December 1791), ...

Perhaps the footnote mark is being mistaken for a date? It looks like the first-sentence date parsing is favors false positives over false negatives, and it should be the other way around, because the Infolab prioritizes precision over recall.

**Comment by fakedrake** [comment]
Hello!
Indeed the problem is that it confuses the annotation for a date. There are actually two separate bugs that appear here. One is indeed the fact that  wikipediabase (see the very last 3 lines of resolvers/paragraph.py) which should be fixed. 

The other one is a problem with [overlay-parse](https://github.com/fakedrake/overlay_parse) which is a separate package that parses dates. It can parse individual dates and date ranges. Wikipedia-base first looks for a date range in the first parentheses. If that fails it falls back to the first date found which in this case is "1" ie "1 AD". The initial version of overlay-parse wasn't able to recognize unicode characters like the em dash so my best guess is that you have an old overlay-parse version installed. The blame for this problem is entirely on me. I hadn't registered it as a package on pypi. It there now and we can change setup.py to enforce `overlay-parse >= 1.1`.

**Comment by alvaromorales** [comment]
`setup.py` is [configured](https://github.com/infolab-csail/WikipediaBase/blob/master/setup.py#L35) to install the latest version of overlay-parse from the master branch on github, not pypi.

I just upgraded to the latest commit (ffca1bc). The Mozart example is still failing, I've added an [issue](https://github.com/fakedrake/overlay_parse/issues/1) to overlay-parse.

**Comment by fakedrake** [comment]
I made a pull request solving this properly. However, the annotation next to Beethoven's supposed birthdate reads:

```
Beethoven was baptised on 17 December. His date of birth was often, in the past, given as 16 December, however this is not known with certainty; his family celebrated his birthday on that date, but there is no documentary evidence that his birth was actually on 16 December.
```

However the answer wikipediabase gives after the pull request is solely [based on the first sentence](https://github.com/fakedrake/WikipediaBase/blob/issue_94/tests/examples.py#L230L231)

**Comment by sherryy** [comment]
I investigated on some BIRTH-DATE and DEATH-DATE parsings. The date parsed from infobox are correct, but when we parse from the first paragraph from the article, these a few test cases are failing.

get "wikibase-person" "Jesus" "DEATH-DATE"
suppose to be: yyyymmdd 00300000
now is: yyyymmdd -00020000

get "wikibase-person" "William Shakespeare" "BIRTH-DATE"
suppose to be: 15640426
now is: 00010000

get "wikibase-person" "Violet Markham" "BIRTH-DATE"
suppose to be: yyyymmdd 18720000
now is: 18721000

get "wikibase-person" "Violet Markham" "DEATH-DATE"
suppose to be: yyyymmdd 19590000
now is: yyyymmdd 19590202

**Comment by sfelshin** [comment]
I see what you mean about Jesus and William Shakespeare, but aren't your two Violet Markham cases backwards?  The first sentence starts "Violet Rosa Markham CH (October 1872 – 2 February 1959)" so it looks to me like `18721000` and `19590202` are correct.

**Comment by sfelshin** [comment]
Note that Jesus's article has been rewritten with a simple birth date, but the death date is still complex and we still mistakenly return a parsed date only.  Also, Plato is another good test case, for both birth and death dates.
